using AiCareerDesk.Web.Data;
using AiCareerDesk.Web.Models;
using AiCareerDesk.Web.Services;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Xunit;
namespace AiCareerDesk.Web.Tests;

public class MigrationUpgradeTests
{
    [SqlServerFact]
    public async Task TailoringMigrationPreservesAnExistingDraft()
    {
        var connection = new SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("TEST_SQL_CONNECTION"))
        {
            InitialCatalog = "CareerUpgrade_" + Guid.NewGuid().ToString("N")
        };
        await using var db = new ApplicationDbContext(new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlServer(connection.ConnectionString).Options);
        var draftId = Guid.NewGuid();
        var ownerId = "upgrade-user";
        try
        {
            await db.GetService<IMigrator>().MigrateAsync("20260914152825_InitialCreate");
            await db.Database.OpenConnectionAsync();
            await using (var command = db.Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = """
                    INSERT INTO AspNetUsers
                    (Id, EmailConfirmed, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
                    VALUES (@owner, 0, 0, 0, 0, 0);
                    INSERT INTO ResumeDrafts
                    (Id, OwnerId, SourceResumeId, SourceJobId, Name, ResumeSnapshot,
                     JobDescriptionSnapshot, Content, CreatedUtc, UpdatedUtc)
                    VALUES (@id, @owner, @resume, @job, 'Existing draft', 'Original resume',
                            'Original job', 'Keep these edits', SYSUTCDATETIME(), SYSUTCDATETIME());
                    """;
                command.Parameters.Add(new SqlParameter("@owner", ownerId));
                command.Parameters.Add(new SqlParameter("@id", draftId));
                command.Parameters.Add(new SqlParameter("@resume", Guid.NewGuid()));
                command.Parameters.Add(new SqlParameter("@job", Guid.NewGuid()));
                await command.ExecuteNonQueryAsync();
            }
            await db.Database.CloseConnectionAsync();
            await db.Database.MigrateAsync();
            var service = new ResumeService(db);
            var draft = (await service.GetDraftAsync(ownerId, draftId))!;
            Assert.Equal("Keep these edits", draft.Content);
            Assert.Equal("Original resume", draft.ResumeSnapshot);
            Assert.Equal("Original job", draft.JobDescriptionSnapshot);
            Assert.Equal(WriteResult.Saved, await service.UpdateDraftAsync(ownerId, draftId,
                new DraftInput { Content = "Edit after upgrade", Version = draft.Version }));
            Assert.NotEqual(draft.Version, (await service.GetDraftAsync(ownerId, draftId))!.Version);
            Assert.False(db.Database.HasPendingModelChanges());
        }
        finally
        {
            // This database name is generated by this test; no caller-supplied database is deleted.
            await db.Database.EnsureDeletedAsync();
        }
    }
}
