using AiCareerDesk.Web.Data;
using AiCareerDesk.Web.Models;
using AiCareerDesk.Web.Services;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Xunit;
namespace AiCareerDesk.Web.Tests;

public class MigrationUpgradeTests
{
    [SqlServerFact]
    public async Task TailoringMigrationPreservesAnExistingDraft()
    {
        var connection = new SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("TEST_SQL_CONNECTION"))
        {
            InitialCatalog = "CareerUpgrade_" + Guid.NewGuid().ToString("N")
        };
        await using var db = new ApplicationDbContext(new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlServer(connection.ConnectionString).Options);
        var draftId = Guid.NewGuid();
        var resumeId = Guid.NewGuid();
        var jobId = Guid.NewGuid();
        var ownerId = "upgrade-user";
        try
        {
            await db.GetService<IMigrator>().MigrateAsync("20260914152825_InitialCreate");
            await db.Database.OpenConnectionAsync();
            await using (var command = db.Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = """
                    INSERT INTO AspNetUsers
                    (Id, EmailConfirmed, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
                    VALUES (@owner, 0, 0, 0, 0, 0);
                    INSERT INTO Jobs
                    (Id, OwnerId, Title, Company, Location, ApplicationUrl, Description, Notes, Status, CreatedUtc, UpdatedUtc)
                    VALUES (@job, @owner, 'Existing job', 'Example', '', '', 'Original job', '', 0, SYSUTCDATETIME(), SYSUTCDATETIME());
                    INSERT INTO Resumes (Id, OwnerId, Name, Content, UpdatedUtc)
                    VALUES (@resume, @owner, 'Existing resume', 'Original resume', SYSUTCDATETIME());
                    INSERT INTO ResumeDrafts
                    (Id, OwnerId, SourceResumeId, SourceJobId, Name, ResumeSnapshot,
                     JobDescriptionSnapshot, Content, CreatedUtc, UpdatedUtc)
                    VALUES (@id, @owner, @resume, @job, 'Existing draft', 'Original resume',
                            'Original job', 'Keep these edits', SYSUTCDATETIME(), SYSUTCDATETIME());
                    """;
                command.Parameters.Add(new SqlParameter("@owner", ownerId));
                command.Parameters.Add(new SqlParameter("@id", draftId));
                command.Parameters.Add(new SqlParameter("@resume", resumeId));
                command.Parameters.Add(new SqlParameter("@job", jobId));
                await command.ExecuteNonQueryAsync();
            }
            await db.Database.CloseConnectionAsync();
            await db.Database.MigrateAsync();
            var service = new ResumeService(db);
            var resume = (await service.GetAsync(ownerId, resumeId))!;
            Assert.Equal("Original resume", resume.Content);
            Assert.Equal(WriteResult.Saved, await service.UpdateAsync(ownerId, resumeId,
                new ResumeInput { Name = resume.Name, Content = "Updated after migration", Version = resume.Version }));
            var jobs = new JobService(db);
            var job = (await jobs.GetAsync(ownerId, jobId))!;
            Assert.Equal("Existing job", job.Title);
            Assert.Equal(WriteResult.Saved, await jobs.UpdateAsync(ownerId, jobId,
                new JobInput { Title = job.Title, Company = job.Company, Status = ApplicationStatus.Applied, Version = job.Version }));
            Assert.Single(await jobs.HistoryAsync(ownerId, jobId));
            var draft = (await service.GetDraftAsync(ownerId, draftId))!;
            Assert.Equal("Keep these edits", draft.Content);
            Assert.Equal("Original resume", draft.ResumeSnapshot);
            Assert.Equal("Original job", draft.JobDescriptionSnapshot);
            Assert.Equal(WriteResult.Saved, await service.UpdateDraftAsync(ownerId, draftId,
                new DraftInput { Content = "Edit after upgrade", Version = draft.Version }));
            Assert.NotEqual(draft.Version, (await service.GetDraftAsync(ownerId, draftId))!.Version);
            Assert.False(db.Database.HasPendingModelChanges());
        }
        finally
        {
            // This database name is generated by this test; no caller-supplied database is deleted.
            await db.Database.EnsureDeletedAsync();
        }
    }
}
