"""Real Chromium workflow test; optional Playwright test dependency."""
import tempfile
import threading
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
from office import make_server, Office, utcnow
from contextlib import closing


def main():
    with tempfile.TemporaryDirectory() as folder:
        server = make_server(Path(folder) / 'browser.sqlite3', 0)
        worker = threading.Thread(target=server.serve_forever, daemon=True)
        worker.start()
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch()
                page = browser.new_page(viewport={'width': 1440, 'height': 1000})
                errors = []
                page.on('pageerror', lambda error: errors.append(str(error)))
                page.goto(f'http://127.0.0.1:{server.server_port}')
                expect(page.get_by_role('status')).to_have_text('Workspace up to date.')
                expect(page.locator('#agents .agent')).to_have_count(12)
                agents = page.locator('#agent-form')
                agents.get_by_label('Name', exact=True).fill('Evidence editor')
                agents.get_by_label('Role / instructions').fill('Check every source.')
                agents.get_by_role('button', name='Save agent').click()
                expect(page.locator('#agents')).to_contain_text('Evidence editor')
                page.get_by_label('Task title').fill('Verify the launch notes')
                page.get_by_label('Brief', exact=True).fill('Check claims and record limits.')
                page.get_by_label('Assigned role').select_option(label='Evidence editor')
                page.get_by_role('button', name='Create task', exact=True).click()
                card = page.locator('article.task').filter(has_text='Verify the launch notes')
                expect(card).to_be_visible()
                card.get_by_role('button', name='Start', exact=True).click()
                expect(card.get_by_role('button', name='Request review')).to_be_visible()
                card.get_by_label('Result / working notes').fill('Claims checked; no live AI provider configured.')
                page.get_by_label('Search tasks').fill('hide everything')
                expect(page.locator('article.task')).to_have_count(0)
                page.get_by_label('Search tasks').fill('launch')
                expect(card.get_by_label('Result / working notes')).to_have_value('Claims checked; no live AI provider configured.')
                card.get_by_label('Assign staff').select_option(label='QA Engineer (0 open)')
                card.get_by_role('button', name='Save changes').click()
                expect(card.locator('.eyebrow')).to_contain_text('QA Engineer')
                card.get_by_role('button', name='Request review').click()
                card.get_by_role('button', name='Approve & complete').click()
                expect(card.get_by_role('button', name='Reopen')).to_be_visible()
                page.reload()
                expect(card.get_by_label('Result / working notes')).to_have_value('Claims checked; no live AI provider configured.')
                page.get_by_label('Search tasks').fill('not present')
                expect(page.locator('article.task')).to_have_count(0)
                page.get_by_label('Search tasks').fill('launch')
                expect(card).to_be_visible()
                page.set_viewport_size({'width': 390, 'height': 844})
                expect(card).to_be_visible()
                assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile overflow'
                # Exercise bounded rendering with real stored tasks.
                office = Office(Path(folder) / 'browser.sqlite3')
                with closing(office.connect()) as db, db:
                    db.executemany('INSERT INTO tasks(title,brief,agent,created) VALUES (?,?,?,?)',
                                   [(f'Batch task {i}', 'Scale verification', 1, utcnow()) for i in range(80)])
                page.get_by_label('Search tasks').fill('')
                page.get_by_role('button', name='Refresh', exact=True).click()
                expect(page.locator('article.task')).to_have_count(26)
                page.get_by_role('button', name='Show more queued').click()
                expect(page.locator('article.task')).to_have_count(51)
                page.get_by_label('Search tasks').fill('Batch task 0')
                expect(page.locator('article.task')).to_have_count(1)
                page.get_by_label('Application project name').fill('Example company — software engineer')
                page.get_by_role('button', name='Create application workflow').click()
                expect(page.locator('#projects')).to_contain_text('0/9 completed')
                page.get_by_label('Search tasks').fill('')
                page.get_by_label('Project', exact=True).select_option(label='Example company — software engineer')
                expect(page.locator('article.task')).to_have_count(9)
                discovery = page.locator('article.task').filter(has=page.get_by_role('heading', name='Discover and verify an opening', exact=True))
                expect(discovery.get_by_role('button', name='Start', exact=True)).to_be_disabled()
                planning = page.locator('article.task').filter(has=page.get_by_role('heading', name='Set application preferences', exact=True))
                planning.get_by_role('button', name='Start', exact=True).click()
                expect(planning.get_by_role('button', name='Request review')).to_be_visible()
                planning.get_by_label('Result / working notes').fill('Synthetic profile verified for test purposes only.')
                planning.get_by_role('button', name='Request review').click()
                planning.get_by_role('button', name='Approve & complete').click()
                expect(discovery.get_by_role('button', name='Start', exact=True)).to_be_enabled()
                expect(page.locator('#projects')).to_contain_text('1/9 completed')
                page.reload()
                expect(page.locator('#projects')).to_contain_text('1/9 completed')
                page.get_by_label('Candidate case name', exact=True).fill('Synthetic placement case')
                page.get_by_label('Candidate intake notes', exact=True).fill('Test profile only; nationwide preferences to confirm.')
                page.get_by_role('button', name='Create candidate case', exact=True).click()
                expect(page.locator('#projects')).to_contain_text('0/12 completed')
                page.get_by_label('Application to protect', exact=True).select_option(label='Example company — software engineer')
                page.get_by_label('Candidate identity', exact=True).select_option(label='Synthetic placement case')
                page.get_by_label('Employer domain', exact=True).fill('example.com')
                page.get_by_label('Employer requisition ID', exact=True).fill('TEST-1')
                page.get_by_role('button', name='Register duplicate protection', exact=True).click()
                expect(page.locator('#projects')).to_contain_text('Duplicate protection: example.com / test-1')
                page.get_by_label('Application', exact=True).select_option(label='Example company — software engineer')
                page.get_by_label('Observed status', exact=True).select_option('submitted')
                page.get_by_label('Evidence or access blocker').fill('Synthetic confirmation REF-TEST; not a real application.')
                page.get_by_label('Next check (local time)', exact=True).fill('2099-01-01T10:00')
                page.get_by_role('button', name='Record application status', exact=True).click()
                expect(page.locator('#projects')).to_contain_text('Recorded status: submitted')
                page.reload()
                expect(page.locator('#projects')).to_contain_text('Recorded status: submitted')
                page.get_by_text('Status evidence and history', exact=True).click()
                expect(page.locator('#projects')).to_contain_text('Synthetic confirmation REF-TEST')
                page.get_by_label('Application project name', exact=True).fill('Linked synthetic opening')
                page.get_by_label('Candidate case (optional)', exact=True).select_option(label='Synthetic placement case')
                page.get_by_role('button', name='Create application workflow', exact=True).click()
                expect(page.locator('#projects')).to_contain_text('2 linked applications')
                page.get_by_label('Application to protect', exact=True).select_option(label='Linked synthetic opening')
                page.get_by_label('Candidate identity', exact=True).select_option(label='Synthetic placement case')
                page.get_by_label('Employer domain', exact=True).fill('EXAMPLE.COM')
                page.get_by_label('Employer requisition ID', exact=True).fill(' test-1 ')
                page.get_by_role('button', name='Register duplicate protection', exact=True).click()
                expect(page.locator('#message')).to_contain_text('Duplicate application: use existing project')

                page.get_by_label('Application', exact=True).select_option(label='Candidate: Synthetic placement case')
                page.get_by_label('Observed status', exact=True).select_option('searching')
                page.get_by_label('Evidence or access blocker').fill('Synthetic search plan approved; no actual applications.')
                page.get_by_role('button', name='Record application status', exact=True).click()
                expect(page.locator('#projects')).to_contain_text('Recorded status: searching')
                page.reload()
                expect(page.locator('#projects')).to_contain_text('2 linked applications')
                expect(page.locator('#projects')).to_contain_text('Recorded status: searching')
                page.get_by_label('Campaign candidate', exact=True).select_option(label='Synthetic placement case')
                page.get_by_label('Employer board tokens', exact=True).fill('example')
                page.get_by_label('Target job titles', exact=True).fill('Software Engineer')
                page.get_by_label('Approved US location phrases', exact=True).fill('United States')
                page.get_by_label('Verified skills', exact=True).fill('C#, SQL Server')
                page.get_by_label('Verified master CV', exact=True).fill('Synthetic test CV: built C# APIs with SQL Server.')
                page.get_by_label('Candidate authorizes this search and use of these CV facts', exact=True).check()
                page.get_by_role('button', name='Save recruiting campaign', exact=True).click()
                expect(page.locator('#campaigns')).to_contain_text('Discovery stopped')
                page.reload()
                page.get_by_label('Campaign candidate', exact=True).select_option(label='Synthetic placement case')
                expect(page.get_by_label('Verified master CV', exact=True)).to_have_value('Synthetic test CV: built C# APIs with SQL Server.')
                page.get_by_label('Chat candidate', exact=True).select_option(label='Synthetic placement case')
                page.get_by_label('Chat staff role', exact=True).select_option(label='Submission Team')
                page.get_by_label('Your message', exact=True).fill('What is my application status and next check?')
                page.get_by_role('button', name='Ask staff assistant', exact=True).click()
                expect(page.locator('#chat-history')).to_contain_text('Recorded status: submitted')
                expect(page.locator('#chat-history')).to_contain_text('Synthetic confirmation REF-TEST')
                expect(page.locator('#chat-history')).to_contain_text('not a live staff member')
                page.reload()
                page.get_by_label('Chat candidate', exact=True).select_option(label='Synthetic placement case')
                page.get_by_label('Chat staff role', exact=True).select_option(label='Submission Team')
                expect(page.locator('#chat-history')).to_contain_text('Recorded status: submitted')
                page.get_by_label('Chat staff role', exact=True).select_option(label='Interview Coaching Team')
                page.get_by_label('Your message', exact=True).fill('What is pending for my interview?')
                page.get_by_role('button', name='Ask staff assistant', exact=True).click()
                expect(page.locator('#chat-history')).to_contain_text('Open work')
                assert not errors, errors
                browser.close()
                print('Chromium: agent creation, task lifecycle, reload persistence, search, mobile layout passed.')
        finally:
            server.shutdown(); worker.join(); server.server_close()


if __name__ == '__main__': main()
